# kubernetes/api.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-api
  template:
    metadata:
      labels:
        app: todo-api
    spec:
      containers:
      - name: todo-api-container
        image: woo45/todo-api
        env:
          - name: USERNAME
            valueFrom:
              secretKeyRef:
                name: secret-api-key
                key: username
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: secret-api-key
                key: password
        volumeMounts:
          - name: task-pv-storage
            mountPath: /data
      volumes:
        - name: task-pv-storage
          persistentVolumeClaim:
            claimName: db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: todo-api
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      name: todo-api-port
  type: LoadBalancer
